name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install-command: npm install
          build: npm run build
          start: npm start
        continue-on-error: true
        
      - name: Generate report
        run: npm run node ./cypress/report.js
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: index
          path: ./cypress/report
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./report
